### ISSUE TITLE
Error While uplaoding file from URL

### ISSUE THREAD

**Issue by Mayur700** [tizz98/py-pspdfkit#5]
Hi Elijah Wilson,

I tried uploading the file from a URL to the PSPDF kit server. But it throws me following error. Please help me the issue.

from pspdfkit import API 
con= API('http://localhost:5000', 'secret')
def uploadDocument():
	documentId = getClientInstance.upload_file_from_url("http://192.168.100.181:8000/static/attachments/taskDocuments/1526478146_example.pdf", "a51f07b7c36a828c592319b4c19ede1686ff29293b4301b9726b61af80c182c4")
	return

But I get the following Error: 
----------------------------------------------------
Traceback (most recent call last):
  File "practicemakesManperfect.py", line 33, in <module>
    uploadDocument()
  File "practicemakesManperfect.py", line 7, in uploadDocument
    "a51f07b7c36a828c592319b4c19ede1686ff29293b4301b9726b61af80c182c4")
  File "/usr/lib/python2.7/site-packages/pspdfkit/api.py", line 50, in upload_file_from_url
    return self._post('documents', json={'url': url, 'sha256': sha256})
  File "/usr/lib/python2.7/site-packages/pspdfkit/api.py", line 106, in _post
    return self._request('post', endpoint, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/pspdfkit/api.py", line 120, in _request
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:5000/api/documents

Thanks for the help.

**Comment by tizz98** [comment]
I realize that I'm 2 years late to respond, but this seems like an internal server error from pspdfkit itself
